/*
 * This source file was generated by the Gradle 'init' task
 */
package telegrambot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void dummyTest() {
        // A placeholder test to ensure the test suite runs.
        // TODO: Add meaningful tests for the application logic.
        assertTrue(true);
    }
}
